# Basic SEN6x Configuration Example
# Minimal setup for quick start

esphome:
  name: sen6x-sensor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO21
  scl: GPIO22
  id: bus_a

external_components:
  - source:
      type: local
      path: components
    components: [sen6x]

sen6x:
  i2c_id: bus_a
  address: 0x6B
  update_interval: 10s

sensor:
  - platform: sen6x
    pm_2_5:
      name: "PM 2.5"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    voc_index:
      name: "VOC Index"
    co2:
      name: "CO2"
