# Basic SEN6x Configuration Example
# Minimal setup for quick start

esphome:
  name: sen6x-sensor

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO21
  scl: GPIO22

external_components:
  - source: github://amzaldua/sen6x_esphome_component
    components: [sen6x]

sen6x:
  address: 0x6B
  update_interval: 10s

sensor:
  - platform: sen6x
    pm_2_5:
      name: "PM 2.5"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    voc_index:
      name: "VOC Index"
    co2:
      name: "CO2"

# Altitude compensation for accurate CO2 readings
number:
  - platform: sen6x
    altitude_compensation:
      name: "Altitude"
