# Full SEN6x Configuration Example
# All available sensors and controls

esphome:
  name: sen6x-full

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO21
  scl: GPIO22

external_components:
  - source: github://amzaldua/sen6x_esphome_component
    components: [sen6x]

sen6x:
  address: 0x6B
  update_interval: 10s

sensor:
  - platform: sen6x
    # Particulate Matter
    pm_1_0:
      name: "PM 1.0"
    pm_2_5:
      name: "PM 2.5"
    pm_4_0:
      name: "PM 4.0"
    pm_10_0:
      name: "PM 10.0"
    # Environmental
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    # Gas Indexes
    voc_index:
      name: "VOC Index"
    nox_index:
      name: "NOx Index"
    co2:
      name: "CO2"
    formaldehyde:
      name: "Formaldehyde"
    # TVOC Estimations (Sensirion AppNote)
    tvoc_well:
      name: "TVOC WELL"
    tvoc_reset:
      name: "TVOC RESET"
    tvoc_ethanol:
      name: "TVOC Ethanol"

binary_sensor:
  - platform: sen6x
    fan_error:
      name: "Fan Error"
    fan_warning:
      name: "Fan Warning"
    gas_error:
      name: "Gas Error"
    rht_error:
      name: "RHT Error"
    pm_error:
      name: "PM Error"
    laser_error:
      name: "Laser Error"
    fan_cleaning_active:
      name: "Fan Cleaning Active"

text_sensor:
  - platform: sen6x
    product_name:
      name: "Product Name"
    serial_number:
      name: "Serial Number"
    status_hex:
      name: "Status Hex"

button:
  - platform: sen6x
    fan_cleaning:
      name: "Start Fan Cleaning"
    device_reset:
      name: "Device Reset"
    force_co2_calibration:
      name: "Force CO2 Calibration"

switch:
  - platform: sen6x
    auto_fan_cleaning:
      name: "Auto Fan Cleaning"
    co2_automatic_self_calibration:
      name: "CO2 Auto Calibration"

number:
  - platform: sen6x
    altitude_compensation:
      name: "Altitude"
    temperature_offset:
      name: "Temperature Offset"
    outdoor_co2_reference:
      name: "Outdoor CO2 Reference"
